### ISSUE TITLE
Tizen Build Fails with NoClassDefFoundError

### ISSUE THREAD

**Issue by bkadirbeyoglu** [Samsung/cordova-plugin-toast#71]
Hello,

The command 
grunt sectv-build:sectv-tizen
fails with the following error, and I am clueless. Thanks in advance.

C:\ToastBurakTest\sampleMedia>grunt sectv-build:sectv-tizen
Running "sectv-build:sectv-tizen" (sectv-build) task

Start packaging Samsung Tizen TV Platform......
Tizen CLI 2.4.44

Setting configuration is succeeded....

Build Web Application:  100% (10/10)

BUILD SUCCESSFUL

Output path : C:\ToastBurakTest\sampleMedia\platforms\sectv-tizen\www\.buildResu
lt
Excluded : [.build/*, .build, .sign/*, .sign, webUnitTest/*, webUnitTest, .exter
nalToolBuilders/*, .externalToolBuilders, .buildResult/*, .buildResult, .setting
s/*, .settings, .package/*, .package, .tproject, .project, .sdk_delta.info, .rds
_delta, *.wgt, .tizen-ui-builder-tool.xml]
Total time: 00:00:00.923
Exception in thread "main" java.lang.NoClassDefFoundError: org/tizen/ssilib/SSIM
acro$Runner
        at org.tizen.ncli.ide.shell.PackageCLI.doPackageForWgt(PackageCLI.java:8
80)
        at org.tizen.ncli.ide.shell.PackageCLI.execute(PackageCLI.java:1227)
        at org.tizen.ncli.ide.shell.AbstractCLI.execute(AbstractCLI.java:91)
        at org.tizen.ncli.ide.shell.Main.run(Main.java:152)
        at org.tizen.ncli.ide.shell.Main.main(Main.java:84)
Caused by: java.lang.ClassNotFoundException: org.tizen.ssilib.SSIMacro$Runner
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 5 more
Fatal error: Exception in thread "main" java.lang.NoClassDefFoundError: org/tize
n/ssilib/SSIMacro$Runner
        at org.tizen.ncli.ide.shell.PackageCLI.doPackageForWgt(PackageCLI.java:8
80)
        at org.tizen.ncli.ide.shell.PackageCLI.execute(PackageCLI.java:1227)
        at org.tizen.ncli.ide.shell.AbstractCLI.execute(AbstractCLI.java:91)
        at org.tizen.ncli.ide.shell.Main.run(Main.java:152)
        at org.tizen.ncli.ide.shell.Main.main(Main.java:84)
Caused by: java.lang.ClassNotFoundException: org.tizen.ssilib.SSIMacro$Runner
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 5 more

**Comment by AnriTapel** [comment]
Hi. Have you resolved this issue? I have the same one and can't find out how to deal with it.
